### ISSUE TITLE
How to do automation?

### ISSUE THREAD

**Issue by LexMrack** [yangqian/hass-cozylife#7]
When creating automation, it is impossible to turn on/off by pressing the zigbee button.
If it is a regular light bulb, then you can select "switch state" in the conditions. Nothing works with this integration.

![cozi](https://github.com/yangqian/hass-cozylife/assets/139388477/3ca7ab40-987b-4c64-895a-03783a7641c2)

**Comment by yangqian** [comment]
Sorry for the late reply. I am not familiar with you UI. But it is exposed to the home assistant as a regular bulb. It is not a zigbee button though.

**Comment by LexMrack** [comment]
Сам решил
